### ISSUE TITLE
Not working on macOS High Sierra version 10.13.6 (17G7024)

### ISSUE THREAD

**Issue by itsStar** [arturogalan/ntfs-mac-automator#1]
Folder action is not loading on macOS High Sierra version 10.13.6 (17G7024)
Please update.

**Comment by support321** [comment]
Same here. 
I'm going to try it on Mojave and Catalina.

**Comment by itsStar** [comment]
Please update the script It is highly appreciated 
OR you can change it to a service to use it by right clicking on NTFS drive and execute from menu

**Comment by arturogalan** [comment]
Thanks for the feedback! I'll try to check it in High Sierra

**Comment by arturogalan** [comment]
It seems that the folder actions doesn't install properly. Please execute `open -a "Folder Actions Setup"` in a console, and see if the action appears.
If don't:
Click in the plus icon
![image](https://user-images.githubusercontent.com/8349083/70156938-f6dfae00-16b4-11ea-964d-4518c2e67e15.png)

Press  Command + Shift + G and put `/Volumes` 

![image](https://user-images.githubusercontent.com/8349083/70157132-5047dd00-16b5-11ea-9bb3-2ed8d18f6886.png)

Then select the donwloaded script

![image](https://user-images.githubusercontent.com/8349083/70157186-6f466f00-16b5-11ea-93d5-9c338735279a.png)

And now you should see something like this:

![image](https://user-images.githubusercontent.com/8349083/70157232-84bb9900-16b5-11ea-8925-eca792298d87.png)

**Comment by itsStar** [comment]
It is attached and open -a "Folder Actions Setup" command works fine but the Drive don't attach with write permission

**Comment by arturogalan** [comment]
so you have Folder Actions Setup as the last screenshot?

**Comment by itsStar** [comment]
<img width="361" alt="Screen Shot 2019-12-04 at 8 54 57 PM" src="https://user-images.githubusercontent.com/13308815/70158051-64e99c80-16d8-11ea-9ef7-f61463a6b4b8.png">
After your suggested steps it launched as a dialogue and asked to connect and then asked for password and after giving the password it fired this error.

**Comment by arturogalan** [comment]
mmm maybe because the volume has no label?. Can you give it a name with right click and rename?

**Comment by itsStar** [comment]
<img width="326" alt="Screen Shot 2019-12-04 at 9 03 24 PM" src="https://user-images.githubusercontent.com/13308815/70158735-8bf49e00-16d9-11ea-95f2-9ad7af901232.png">

I have given it name NTFS32GB in it give the following error

**Comment by arturogalan** [comment]
Have you any other NTFS stick to try with? this 'failed to mount' message is a system message and maybe is damaged

**Comment by itsStar** [comment]
i have just formatted this successfully

**Comment by itsStar** [comment]
i have attached an other NTFS device and it didn't start the service :)

**Comment by arturogalan** [comment]
Hi, I've made a quick action to be able to run the script with right click in Finder->quick actions over the volume, can you test it? Thanks!

https://github.com/arturogalan/ntfs-mac-automator/raw/master/NTFS%20writable%20utility%20SERVICE.zip

**Comment by itsStar** [comment]
I have tested it on 2 platforms 
1: 
<img width="273" alt="Screenshot 2019-12-18 at 3 15 11 PM" src="https://user-images.githubusercontent.com/13308815/71077698-bea69800-21a9-11ea-8be7-0798d196f7df.png">
Error is as follows 
<img width="428" alt="Screenshot 2019-12-18 at 3 14 53 PM" src="https://user-images.githubusercontent.com/13308815/71077729-cebe7780-21a9-11ea-86c8-d3c8b0e47249.png">
2:
<img width="321" alt="Screen Shot 2019-12-18 at 3 20 07 PM" src="https://user-images.githubusercontent.com/13308815/71077789-ec8bdc80-21a9-11ea-91b2-07f80898be87.png">
Error as follows 
<img width="431" alt="Screen Shot 2019-12-18 at 3 11 09 PM" src="https://user-images.githubusercontent.com/13308815/71077840-0cbb9b80-21aa-11ea-8e15-2519be1d8ca2.png">

Please check 
Thanks.

**Comment by arturogalan** [comment]
Can you please execute 
diskutil list
in the command line with the volume attached, and put here the result? thanks

**Comment by itsStar** [comment]
Here is the result:

 diskutil list
/dev/disk0 (internal):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                         251.0 GB   disk0
   1:                        EFI EFI                     314.6 MB   disk0s1
   2:                 Apple_APFS Container disk2         85.0 GB    disk0s2
   3:                 Apple_APFS Container disk1         40.1 GB    disk0s3
   4:                  Apple_HFS Star's Vault            125.4 GB   disk0s4

/dev/disk1 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +40.1 GB    disk1
                                 Physical Store disk0s3
   1:                APFS Volume WorkSpace               37.5 GB    disk1s1

/dev/disk2 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +85.0 GB    disk2
                                 Physical Store disk0s2
   1:                APFS Volume Mac                     67.1 GB    disk2s1
   2:                APFS Volume Preboot                 59.6 MB    disk2s2
   3:                APFS Volume Recovery                1.5 GB     disk2s3
   4:                APFS Volume VM                      6.4 GB     disk2s4

/dev/disk3 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *1.0 TB     disk3
   1:                        EFI EFI                     209.7 MB   disk3s1
   2:       Microsoft Basic Data NTFS                    100.4 GB   disk3s2
   3:                  Apple_HFS Backup Drive            899.3 GB   disk3s3

**Comment by arturogalan** [comment]
Ok, it seems that your external disc is in GPT format instead of MBR, that's why the type is _Microsoft Basic Data_ instead of _Windows_NTFS_. 
Maybe it has been used as a system drive. I didn't found a fast way to convert the volume to MBR in mac, and it seems that fstab doesn't support this type to make it writable, so the only thing you could do is follow this steps in a Windows computer to change the type:
**Should do before a backup if you have data in there.**

In the windows command line:

diskpart (press enter)
list disk (press enter and remember the number of the disk you want to convert-> 2 for example)
select disk 2 (press enter)
clean (press enter)
convert mbr (press enter)
exit (press enter)

**Comment by itsStar** [comment]
Thanks.
